name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allow manual trigger of the workflow


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Docker Tag
      id: docker-tag
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]; then
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/net-datascience:${{ env.TAG }}

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/net-datascience:${{ env.TAG }}
